# CalistaLife Netlify Configuration
[build]
  base = "frontend"
  command = "npm ci --production && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
  # Security settings
  NETLIFY_SKIP_SCANS = "false"
  
  # Secret scanning exclusions (safe patterns)
  NETLIFY_SECRET_SCAN_EXCLUDE_PATTERNS = "VITE_BREVO_CLIENT_KEY,js-tokens,calistasecretstoreewfsdca"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://api.calistalife.com/:splat"
  status = 200
  force = true

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific settings
[context.production]
  command = "npm ci --production && npm run build"
  
[context.deploy-preview]
  command = "npm ci && npm run build"