# CalistaLife Netlify Configuration
# Note: SECRETS_SCAN_* variables must be set in Netlify UI under Site Settings > Environment Variables

[build]
  base = "frontend"
  command = "npm ci --production && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Secrets scanning configuration
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_GA4_MEASUREMENT_ID,VITE_SENTRY_DSN,VITE_API_URL,VITE_APP_ENV"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,**/*.js.map,index.html,.env.example,WARP.md,src/**"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://api.calistalife.com/:splat"
  status = 200
  force = true

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific settings
[context.production]
  command = "npm ci --production && npm run build"
  [context.production.environment]
    SECRETS_SCAN_ENABLED = "false"
    SECRETS_SCAN_OMIT_KEYS = "VITE_GA4_MEASUREMENT_ID,VITE_SENTRY_DSN,VITE_API_URL,VITE_APP_ENV"
    SECRETS_SCAN_OMIT_PATHS = "dist/**,**/*.js.map,index.html,.env.example,WARP.md,src/**"
  
[context.deploy-preview]
  command = "npm ci && npm run build"
  [context.deploy-preview.environment]
    SECRETS_SCAN_ENABLED = "false"
    SECRETS_SCAN_OMIT_KEYS = "VITE_GA4_MEASUREMENT_ID,VITE_SENTRY_DSN,VITE_API_URL,VITE_APP_ENV"
    SECRETS_SCAN_OMIT_PATHS = "dist/**,**/*.js.map,index.html,.env.example,WARP.md,src/**"
