# CalistaLife Netlify Configuration
# Frontend environment variables (VITE_*) are public by design and safe for browser use

[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  # Exclude legitimate frontend environment variables from secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_APP_ENV,VITE_GA4_MEASUREMENT_ID,VITE_SENTRY_DSN,VITE_API_URL,VITE_FACEBOOK_PIXEL_ID,VITE_GOOGLE_ADS_ID,VITE_BREVO_CLIENT_KEY,VITE_ENABLE_BREVO_CHAT"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://api.calistalife.com/:splat"
  status = 200
  force = true

# SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
